development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dbuser
  password: dbpass
  timeout: 5000
  database: dbreview

test:
  <<: *default
  database: dbreview_test

production:
  <<: *default
  database: dbreview_production
